/* Generated By:JavaCC: Do not edit this line. LexerConstants.java */
package lexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS = 1;
  /** RegularExpression Id. */
  int EXTENDS = 2;
  /** RegularExpression Id. */
  int WHILE = 3;
  /** RegularExpression Id. */
  int IF = 4;
  /** RegularExpression Id. */
  int ELSE = 5;
  /** RegularExpression Id. */
  int FOR = 6;
  /** RegularExpression Id. */
  int NEW = 7;
  /** RegularExpression Id. */
  int RETURN = 8;
  /** RegularExpression Id. */
  int INT_CONST = 37;
  /** RegularExpression Id. */
  int BOOLEAN_CONST = 38;
  /** RegularExpression Id. */
  int STRING_CONST = 39;
  /** RegularExpression Id. */
  int ID = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"class\"",
    "\"extends\"",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\"for\"",
    "\"new\"",
    "\"return\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"/*\"",
    "\"*\"",
    "\"<\"",
    "\">\"",
    "\"!\"",
    "<token of kind 28>",
    "\"%\"",
    "<token of kind 30>",
    "\";\"",
    "\".\"",
    "\",\"",
    "\"||\"",
    "\"&&\"",
    "\"\\\"\"",
    "<INT_CONST>",
    "<BOOLEAN_CONST>",
    "<STRING_CONST>",
    "<ID>",
    "<token of kind 41>",
    "<token of kind 42>",
    "<token of kind 43>",
  };

}
