/* Generated By:JavaCC: Do not edit this line. LexerConstants.java */
package lexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS = 1;
  /** RegularExpression Id. */
  int EXTENDS = 2;
  /** RegularExpression Id. */
  int NEW = 3;
  /** RegularExpression Id. */
  int LTE = 4;
  /** RegularExpression Id. */
  int GTE = 5;
  /** RegularExpression Id. */
  int EQUAL = 6;
  /** RegularExpression Id. */
  int NOTEQUAL = 7;
  /** RegularExpression Id. */
  int LPAREN = 8;
  /** RegularExpression Id. */
  int RPAREN = 9;
  /** RegularExpression Id. */
  int LBRACKET = 10;
  /** RegularExpression Id. */
  int RBRACKET = 11;
  /** RegularExpression Id. */
  int LSQBRACKET = 12;
  /** RegularExpression Id. */
  int RSQBRACKET = 13;
  /** RegularExpression Id. */
  int ASSIGN = 14;
  /** RegularExpression Id. */
  int PLUS = 15;
  /** RegularExpression Id. */
  int MINUS = 16;
  /** RegularExpression Id. */
  int FSLASH = 17;
  /** RegularExpression Id. */
  int BSLASH = 18;
  /** RegularExpression Id. */
  int MULT = 19;
  /** RegularExpression Id. */
  int LT = 20;
  /** RegularExpression Id. */
  int GT = 21;
  /** RegularExpression Id. */
  int NOT = 22;
  /** RegularExpression Id. */
  int AT = 23;
  /** RegularExpression Id. */
  int HASHTAG = 24;
  /** RegularExpression Id. */
  int DSIGN = 25;
  /** RegularExpression Id. */
  int PERCENT = 26;
  /** RegularExpression Id. */
  int EXPONENT = 27;
  /** RegularExpression Id. */
  int INT_CONST = 28;
  /** RegularExpression Id. */
  int BOOLEAN_CONST = 29;
  /** RegularExpression Id. */
  int STRING_CONST = 30;
  /** RegularExpression Id. */
  int ID = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"class\"",
    "\"extends\"",
    "\"new\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"\\\\\"",
    "\"*\"",
    "\"<\"",
    "\">\"",
    "\"!\"",
    "\"@\"",
    "\"#\"",
    "\"$\"",
    "\"%\"",
    "\"^\"",
    "<INT_CONST>",
    "<BOOLEAN_CONST>",
    "\"\\\"([a-zA-Z0-9])*\\\"\"",
    "\"Boo\"",
  };

}
